// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCol6dz2FnuF1yUP4lKl5t_EpPc7HPjJR4',
    appId: '1:525916185463:web:56b675df0a532b54d1b772',
    messagingSenderId: '525916185463',
    projectId: 'gofit-fd5d2',
    authDomain: 'gofit-fd5d2.firebaseapp.com',
    storageBucket: 'gofit-fd5d2.firebasestorage.app',
    measurementId: 'G-457WKZTGZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkAfj4YkQxdwe8ZkbyZSo4XgSrLzXdmCw',
    appId: '1:525916185463:android:bd7ef7fa5708f8cbd1b772',
    messagingSenderId: '525916185463',
    projectId: 'gofit-fd5d2',
    storageBucket: 'gofit-fd5d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxVi_N4iEa6D6g6z5WxpkbPjBohQp2cUY',
    appId: '1:525916185463:ios:aa4c4924aaff6cd4d1b772',
    messagingSenderId: '525916185463',
    projectId: 'gofit-fd5d2',
    storageBucket: 'gofit-fd5d2.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxVi_N4iEa6D6g6z5WxpkbPjBohQp2cUY',
    appId: '1:525916185463:ios:aa4c4924aaff6cd4d1b772',
    messagingSenderId: '525916185463',
    projectId: 'gofit-fd5d2',
    storageBucket: 'gofit-fd5d2.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCol6dz2FnuF1yUP4lKl5t_EpPc7HPjJR4',
    appId: '1:525916185463:web:e153c0f647bb9fa1d1b772',
    messagingSenderId: '525916185463',
    projectId: 'gofit-fd5d2',
    authDomain: 'gofit-fd5d2.firebaseapp.com',
    storageBucket: 'gofit-fd5d2.firebasestorage.app',
    measurementId: 'G-ZX7PN25BZ4',
  );
}
